/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2023-02-05 17:04:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_002dlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/main-navbar.jsp", Long.valueOf(1675528930653L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".form-style-1 {\r\n");
      out.write("	margin:10px auto;\r\n");
      out.write("	max-width: 400px;\r\n");
      out.write("	padding: 20px 12px 10px 20px;\r\n");
      out.write("	font: 13px \"Lucida Sans Unicode\", \"Lucida Grande\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 li {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	display: block;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	margin: 10px 0 0 0;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 label{\r\n");
      out.write("	margin:0 0 3px 0;\r\n");
      out.write("	padding:0px;\r\n");
      out.write("	display:block;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 input[type=text],\r\n");
      out.write(".form-style-1 input[type=password], \r\n");
      out.write(".form-style-1 input[type=date],\r\n");
      out.write(".form-style-1 input[type=datetime],\r\n");
      out.write(".form-style-1 input[type=number],\r\n");
      out.write(".form-style-1 input[type=search],\r\n");
      out.write(".form-style-1 input[type=time],\r\n");
      out.write(".form-style-1 input[type=url],\r\n");
      out.write(".form-style-1 input[type=email],\r\n");
      out.write("textarea, \r\n");
      out.write("select{\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	-webkit-box-sizing: border-box;\r\n");
      out.write("	-moz-box-sizing: border-box;\r\n");
      out.write("	border:1px solid #BEBEBE;\r\n");
      out.write("	padding: 7px;\r\n");
      out.write("	margin:0px;\r\n");
      out.write("	-webkit-transition: all 0.30s ease-in-out;\r\n");
      out.write("	-moz-transition: all 0.30s ease-in-out;\r\n");
      out.write("	-ms-transition: all 0.30s ease-in-out;\r\n");
      out.write("	-o-transition: all 0.30s ease-in-out;\r\n");
      out.write("	outline: none;	\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 input[type=text]:focus,\r\n");
      out.write(".form-style-1 input[type=date]:focus,\r\n");
      out.write(".form-style-1 input[type=password]:focus, \r\n");
      out.write(".form-style-1 input[type=date]:focus,\r\n");
      out.write(".form-style-1 input[type=datetime]:focus,\r\n");
      out.write(".form-style-1 input[type=number]:focus,\r\n");
      out.write(".form-style-1 input[type=search]:focus,\r\n");
      out.write(".form-style-1 input[type=time]:focus,\r\n");
      out.write(".form-style-1 input[type=url]:focus,\r\n");
      out.write(".form-style-1 input[type=email]:focus,\r\n");
      out.write(".form-style-1 textarea:focus, \r\n");
      out.write(".form-style-1 select:focus{\r\n");
      out.write("	-moz-box-shadow: 0 0 8px #88D5E9;\r\n");
      out.write("	-webkit-box-shadow: 0 0 8px #88D5E9;\r\n");
      out.write("	box-shadow: 0 0 8px #88D5E9;\r\n");
      out.write("	border: 1px solid #88D5E9;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 .field-divided{\r\n");
      out.write("	width: 49%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-style-1 .field-long{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 .field-select{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 .field-textarea{\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 input[type=submit], .form-style-1 input[type=button]{\r\n");
      out.write("	background: #4B99AD;\r\n");
      out.write("	padding: 8px 15px 8px 15px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 input[type=submit]:hover, .form-style-1 input[type=button]:hover{\r\n");
      out.write("	background: #4691A4;\r\n");
      out.write("	box-shadow:none;\r\n");
      out.write("	-moz-box-shadow:none;\r\n");
      out.write("	-webkit-box-shadow:none;\r\n");
      out.write("}\r\n");
      out.write(".form-style-1 .required{\r\n");
      out.write("	color:red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/navcss.css\">\r\n");
      out.write("<style>\r\n");
      out.write("nav ul {\r\n");
      out.write("  list-style-type: none;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #333;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li {\r\n");
      out.write("  float: left;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("nav li a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 16px;\r\n");
      out.write("  \r\n");
      out.write("  font-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav ul li a{\r\n");
      out.write("text-decoration: none!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<ul>\r\n");
      out.write("			 \r\n");
      out.write("			  <li><a href=\"#home\">Home</a></li>\r\n");
      out.write("			  <li><a href=\"customer-register.jsp\">Register</a></li>\r\n");
      out.write("			  <li><a href=\"#contact\">Login</a></li>\r\n");
      out.write("			  <li><a href=\"#about\">About</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"getData\" method=\"post\">\r\n");
      out.write("<ul class=\"form-style-1\">\r\n");
      out.write("	<li style=\"color:red; font-weight:bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</li>\r\n");
      out.write("    \r\n");
      out.write("    <li>\r\n");
      out.write("        <label>Email <span class=\"required\">*</span></label>\r\n");
      out.write("        <input type=\"email\" name=\"field1\" class=\"field-long\" required/>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <li>\r\n");
      out.write("        <label>Password<span class=\"required\">*</span></label>\r\n");
      out.write("        <input type=\"password\" name=\"field2\" class=\"field-long\" required/>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li>\r\n");
      out.write("        \r\n");
      out.write("        <input type=\"hidden\" name=\"action\" value=\"login\"/>\r\n");
      out.write("        <input type=\"submit\" value=\"Login\" />\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("</ul>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
